# Generated by Django 3.1.5 on 2021-02-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0002_auto_20210204_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='created',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='basketline',
            name='created',
        ),
        migrations.RemoveField(
            model_name='basketline',
            name='modified',
        ),
    ]
