# Generated by Django 3.1.5 on 2021-02-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Category',
            new_name='category',
        ),
    ]
