# Generated by Django 3.1.5 on 2021-02-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_catalog', '0003_auto_20210204_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='created',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='modified',
        ),
    ]
