# Generated by Django 3.1.5 on 2021-02-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_catalog', '0001_initial'),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_catalog.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='ticket_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
