# Generated by Django 3.1.5 on 2021-02-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_auto_20210204_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='modified',
        ),
    ]
